from setuptools import setup, find_packages

setup(name='ack-mcp-server',
      version='0.0.1',
      description='alibabacloud ack mcp server',
      author='KeyOfSpectator',
      author_email='KeyOfSpectator@zju.edu.cn',
      install_requires=['aiofiles', 'aiohappyeyeballs', 'aiohttp', 'aiosignal', 'alibabacloud-credentials',
                        'alibabacloud-credentials-api', 'alibabacloud-cs20151215', 'alibabacloud-darabonba-array',
                        'alibabacloud-darabonba-encode-util', 'alibabacloud-darabonba-map',
                        'alibabacloud-darabonba-signature-util', 'alibabacloud-darabonba-string', 'alibabacloud-endpoint-util',
                        'alibabacloud-gateway-sls', 'alibabacloud-gateway-sls-util', 'alibabacloud-gateway-spi',
                        'alibabacloud-openapi-util', 'alibabacloud-sls20201230', 'alibabacloud-sts20150401', 'alibabacloud-tea',
                        'alibabacloud-tea-openapi', 'alibabacloud-tea-util', 'aliyun-python-sdk-core', 'aliyun-python-sdk-cs',
                        'aliyun-python-sdk-sts', 'annotated-types', 'anyio', 'apscheduler', 'attrs', 'authlib', 'cachetools',
                        'certifi', 'cffi', 'charset-normalizer', 'click', 'cryptography', 'cyclopts', 'darabonba-core',
                        'distro', 'dnspython', 'docstring-parser', 'docutils', 'durationpy', 'email-validator',
                        'exceptiongroup', 'fastapi', 'frozenlist', 'google-auth', 'h11', 'httpcore', 'httptools', 'httpx',
                        'httpx-sse', 'idna', 'iniconfig', 'isodate', 'jiter', 'jmespath', 'jsonschema', 'jsonschema-path',
                        'jsonschema-specifications', 'kubernetes', 'lazy-object-proxy', 'loguru', 'lz4', 'markdown-it-py',
                        'markupsafe', 'mcp', 'mdurl', 'more-itertools', 'multidict', 'oauthlib', 'openai', 'openapi-core',
                        'openapi-pydantic', 'openapi-schema-validator', 'openapi-spec-validator', 'packaging', 'parse',
                        'pathable', 'pluggy', 'propcache', 'pyasn1', 'pyasn1-modules', 'pycparser', 'pydantic', 'pydantic-core',
                        'pydantic-settings', 'pygments', 'pyperclip', 'pytest', 'pytest-asyncio', 'python-dateutil',
                        'python-dotenv', 'python-multipart', 'pyyaml', 'referencing', 'requests', 'requests-oauthlib',
                        'rfc3339-validator', 'rich', 'rich-rst', 'rpds-py', 'rsa', 'six', 'sniffio', 'sse-starlette',
                        'starlette', 'tenacity', 'tqdm', 'typing-extensions', 'typing-inspection', 'tzlocal', 'urllib3',
                        'uvicorn', 'uvloop', 'watchfiles', 'websocket-client', 'websockets', 'werkzeug', 'yarl', 'zstd'],
      packages=find_packages(),
      license="apache 2.0"
      )
