apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: case3-app
  name: case3-app
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: case3-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: case3-app
    spec:
      containers:
        - args:
            - --vm
            - "1"
            - --vm-bytes
            - 16M
            - --timeout
            - 3600s
          ## progrium/stress:latest
          image: registry-cn-beijing.ack.aliyuncs.com/acs/docker-stress:v1.0.1-f69a43e-aliyun
          imagePullPolicy: Always
          name: ugly-container
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          securityContext:
            privileged: true
      hostNetwork: true
      hostPID: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
