{{- define "proxy-config" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mcp-chart.fullname" . }}-proxy-config
data:
  example.json: |
    {
      "mcpProxy": {
        "baseURL": "/",
        "addr": ":9090",
        "name": "MCP Proxy",
        "version": "1.0.0",
        "type": "streamable-http",
        "options": {
          "panicIfInvalid": false,
          "logEnabled": true,
          "authTokens": []
        }
      },
      "mcpServers": {
        "k8s-mcp-server": {
          "k8s-mcp-server": "sse",
          "url": "http://{{ include "mcp-chart.fullname" . }}-k8s-mcp-server:8080/sse/"
        },
        "obs-mcp-server": {
          "obs-mcp-server": "sse",
          "url": "http://{{ include "mcp-chart.fullname" . }}-obs-mcp-server:8080/sse/"
        }
      }
    }
{{- end }}

{{- if .Values.mcpProxy.enabled }}
{{ template "proxy-config" . }}
{{- end }}