apiVersion: apps/v1
kind: Deployment
metadata:
  name: ack-mcp-server
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "ack-mcp-server.name" . }}
    component: ack-mcp-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ack-mcp-server.name" . }}
      component: ack-mcp-server
  template:
    metadata:
      labels:
        app: {{ include "ack-mcp-server.name" . }}
        component: ack-mcp-server
    spec:
      containers:
        - name: ack-mcp-server
          image: "{{ .Values.image.registry }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "ack-mcp-server.fullname" . }}-credentials
                  key: accessKeyId
            - name: ACCESS_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "ack-mcp-server.fullname" . }}-credentials
                  key: accessKeySecret
          ports:
            - name: http
              containerPort: {{ .Values.obsMcpServer.port }}
              protocol: TCP
