apiVersion: v1
kind: Service
metadata:
  name: case5-service
  labels:
    app: case5-service
spec:
  selector:
    app: case5-app
  ports:
    - protocol: TCP
      name: http
      port: 6666
      targetPort: 6666
  type: NodePort