# Default values for mcp-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Required: Alibaba Cloud Access Key ID
accessKeyId: "your-access-key-id"
# Required: Alibaba Cloud Access Key Secret
accessKeySecret: "your-access-key-secret"
image:
  registry: registry.cn-hangzhou.aliyuncs.com/acs/ack-mcp-server
  tag: ""
  pullPolicy: Always
port: 8000
# Probes (disabled as per requirements)
livenessProbe: { }
readinessProbe: { }

serviceAccount:
  create: true
  annotations: { }

# Replica count for each service
replicaCount: 1

# Ingress configuration
ingress:
  enabled: true
  className: alb
  annotations: {}
  hosts:
    - host: ""
      paths:
        - path: /
          pathType: Prefix
