apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: case1-app
  name: case1-app
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: case1-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: case1-app
    spec:
      containers:
        - args:
            - --vm
            - "1"
            - --vm-bytes
            - 80M
            - --timeout
            - 3600s
          ## progrium/stress:latest
          image: registry-cn-beijing.ack.aliyuncs.com/acs/docker-stress:v1.0.1-f69a43e-aliyun
          imagePullPolicy: Always
          name: main-container
          resources:
            limits:
              memory: 64Mi
            requests:
              memory: 16Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
