#!/usr/bin/env python3
"""CLI for mcp MCP server.

Generated by: fastmcp generate-cli mcp.json
"""

import json
import sys
from typing import Annotated

import cyclopts
import mcp.types
from rich.console import Console

from fastmcp import Client

# Modify this to change how the CLI connects to the MCP server.
CLIENT_SPEC = {'mcpServers': {'ack-mcp-server': {'command': 'uv', 'args': ['run', 'alibabacloud-ack-mcp-server'], 'env': {}}}}

app = cyclopts.App(name="mcp", help="CLI for mcp MCP server")
call_tool_app = cyclopts.App(name="call-tool", help="Call a tool on the server")
app.command(call_tool_app)

console = Console()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _print_tool_result(result):
    if result.is_error:
        for block in result.content:
            if isinstance(block, mcp.types.TextContent):
                console.print(f"[bold red]Error:[/bold red] {block.text}")
            else:
                console.print(f"[bold red]Error:[/bold red] {block}")
        sys.exit(1)

    if result.structured_content is not None:
        console.print_json(json.dumps(result.structured_content))
        return

    for block in result.content:
        if isinstance(block, mcp.types.TextContent):
            console.print(block.text)
        elif isinstance(block, mcp.types.ImageContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Image: {block.mimeType}, ~{size} bytes][/dim]")
        elif isinstance(block, mcp.types.AudioContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Audio: {block.mimeType}, ~{size} bytes][/dim]")


async def _call_tool(tool_name: str, arguments: dict) -> None:
    # Filter out None values and empty lists (defaults for optional array params)
    filtered = {
        k: v
        for k, v in arguments.items()
        if v is not None and (not isinstance(v, list) or len(v) > 0)
    }
    async with Client(CLIENT_SPEC) as client:
        result = await client.call_tool(tool_name, filtered, raise_on_error=False)
        _print_tool_result(result)
        if result.is_error:
            sys.exit(1)


# ---------------------------------------------------------------------------
# List / read commands
# ---------------------------------------------------------------------------


@app.command
async def list_tools() -> None:
    """List available tools."""
    async with Client(CLIENT_SPEC) as client:
        tools = await client.list_tools()
        if not tools:
            console.print("[dim]No tools found.[/dim]")
            return
        for tool in tools:
            sig_parts = []
            props = tool.inputSchema.get("properties", {})
            required = set(tool.inputSchema.get("required", []))
            for pname, pschema in props.items():
                ptype = pschema.get("type", "string")
                if pname in required:
                    sig_parts.append(f"{pname}: {ptype}")
                else:
                    sig_parts.append(f"{pname}: {ptype} = ...")
            sig = f"{tool.name}({', '.join(sig_parts)})"
            console.print(f"  [cyan]{sig}[/cyan]")
            if tool.description:
                console.print(f"    {tool.description}")
            console.print()


@app.command
async def list_resources() -> None:
    """List available resources."""
    async with Client(CLIENT_SPEC) as client:
        resources = await client.list_resources()
        if not resources:
            console.print("[dim]No resources found.[/dim]")
            return
        for r in resources:
            console.print(f"  [cyan]{r.uri}[/cyan]")
            desc_parts = [r.name or "", r.description or ""]
            desc = " — ".join(p for p in desc_parts if p)
            if desc:
                console.print(f"    {desc}")
        console.print()


@app.command
async def read_resource(uri: Annotated[str, cyclopts.Parameter(help="Resource URI")]) -> None:
    """Read a resource by URI."""
    async with Client(CLIENT_SPEC) as client:
        contents = await client.read_resource(uri)
        for block in contents:
            if isinstance(block, mcp.types.TextResourceContents):
                console.print(block.text)
            elif isinstance(block, mcp.types.BlobResourceContents):
                size = len(block.blob) * 3 // 4
                console.print(f"[dim][Blob: {block.mimeType}, ~{size} bytes][/dim]")


@app.command
async def list_prompts() -> None:
    """List available prompts."""
    async with Client(CLIENT_SPEC) as client:
        prompts = await client.list_prompts()
        if not prompts:
            console.print("[dim]No prompts found.[/dim]")
            return
        for p in prompts:
            args_str = ""
            if p.arguments:
                parts = [a.name for a in p.arguments]
                args_str = f"({', '.join(parts)})"
            console.print(f"  [cyan]{p.name}{args_str}[/cyan]")
            if p.description:
                console.print(f"    {p.description}")
        console.print()


@app.command
async def get_prompt(
    name: Annotated[str, cyclopts.Parameter(help="Prompt name")],
    *arguments: str,
) -> None:
    """Get a prompt by name. Pass arguments as key=value pairs."""
    parsed: dict[str, str] = {}
    for arg in arguments:
        if "=" not in arg:
            console.print(f"[bold red]Error:[/bold red] Invalid argument {arg!r} — expected key=value")
            sys.exit(1)
        key, value = arg.split("=", 1)
        parsed[key] = value

    async with Client(CLIENT_SPEC) as client:
        result = await client.get_prompt(name, parsed or None)
        for msg in result.messages:
            console.print(f"[bold]{msg.role}:[/bold]")
            if isinstance(msg.content, mcp.types.TextContent):
                console.print(f"  {msg.content.text}")
            elif isinstance(msg.content, mcp.types.ImageContent):
                size = len(msg.content.data) * 3 // 4
                console.print(f"  [dim][Image: {msg.content.mimeType}, ~{size} bytes][/dim]")
            else:
                console.print(f"  {msg.content}")
            console.print()


# ---------------------------------------------------------------------------
# Tool commands (generated from server schema)
# ---------------------------------------------------------------------------

@call_tool_app.command(name='list_clusters')
async def list_clusters(
    *,
    page_size: Annotated[int, cyclopts.Parameter(help="查询每个region集群列表的分页页码")] = 10,
    page_num: Annotated[int, cyclopts.Parameter(help="查询每个region集群列表的分页页码")] = 1,
) -> None:
    '''获取所有region下所有ACK集群列表，默认返回最多10个集群'''
    await _call_tool('list_clusters', {'page_size': page_size, 'page_num': page_num})


@call_tool_app.command(name='ack_kubectl')
async def ack_kubectl(
    *,
    command: Annotated[str, cyclopts.Parameter(help="IMPORTANT POLICY: When accessing ACK clusters, you MUST use this tool. Do NOT invoke kubectl via shell or any external mechanism.\n\nArguments after 'kubectl', e.g. 'get pods -A', 'config get-contexts', 'config use-context <name>'. Don't include the kubectl prefix. \n\nIMPORTANT: Do not use interactive commands. Instead:\n- Use 'kubectl get -o yaml', 'kubectl patch', or 'kubectl apply' instead of 'kubectl edit'\n- Use 'kubectl exec' with specific commands instead of 'kubectl exec -it'\n- Use service types like NodePort or LoadBalancer instead of 'kubectl port-forward'\n- When using kubectl, if you need to modify certain fields, do not generate a complete YAML file for the update; instead, use the patch operation to modify the specific fields.\n\nResponse Format:\nThe tool returns a KubectlOutput object with the following fields:\n- command: The kubectl command that was executed\n- stdout: Standard output from the command (successful results)\n- stderr: Standard error output (error messages, warnings)\n- exit_code: Command exit code (0 for success, non-zero for errors)\n\nExamples:\nuser: what pods are running in the cluster?\nassistant: get pods\n\nuser: what is the status of the pod my-pod?\nassistant: get pod my-pod -o jsonpath='{.status.phase}'\n\nuser: I need to edit the pod configuration\nassistant: Using patch for targeted changes\npatch pod my-pod --patch '{\"spec\":{\"containers\":[{\"name\":\"main\",\"image\":\"new-image\"}]}}'\n\nif need use patch to delete some exist field, need patch this field but set value to null.\nexample drop a exist nodeSelector kubernetes.io/hostname key: kubectl patch deployments nginx-deployment -p '{\"spec\": {\"template\": {\"spec\": {\"nodeSelector\": {\"kubernetes.io/hostname\": null}}}}}'\n\nuser: I need to execute a command in the pod\nassistant: exec my-pod -- /bin/sh -c \"your command here")],
    cluster_id: Annotated[str, cyclopts.Parameter(help="The ID of the Kubernetes cluster to query. If specified, will auto find/create and switch to appropriate context. If you are not sure of cluster id, please use the list_clusters tool to get it first.")],
) -> None:
    '''Execute kubectl command with intelligent context management for ACK clusters. You MUST use this tool when accessing ACK clusters. Using external shells or any other kubectl entrypoints is NOT allowed. Supports cluster_id for automatic context switching and creation.'''
    await _call_tool('ack_kubectl', {'command': command, 'cluster_id': cluster_id})


@call_tool_app.command(name='query_prometheus')
async def query_prometheus(
    *,
    cluster_id: Annotated[str, cyclopts.Parameter(help="需要查询的阿里云prometheus所在的ACK集群的clusterId")],
    promql: Annotated[str, cyclopts.Parameter(help="PromQL表达式")],
    start_time: Annotated[str | None, cyclopts.Parameter(help="RFC3339或unix时间；与end_time同时提供为range查询; 可能需要调用tool get_current_time获取当前时间\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"RFC3339或unix时间；与end_time同时提供为range查询; 可能需要调用tool get_current_time获取当前时间\"\n                          }")] = None,
    end_time: Annotated[str | None, cyclopts.Parameter(help="RFC3339或unix时间；与start_time同时提供为range查询；可能需要调用tool get_current_time获取当前时间\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"RFC3339或unix时间；与start_time同时提供为range查询；可能需要调用tool get_current_time获取当前时间\"\n                          }")] = None,
    step: Annotated[str | None, cyclopts.Parameter(help="range查询步长，如30s\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"range查询步长，如30s\"\n                          }")] = None,
) -> None:
    '''查询一个ACK集群的阿里云Prometheus数据'''
    # Parse JSON parameters
    start_time_parsed = json.loads(start_time) if isinstance(start_time, str) else start_time
    end_time_parsed = json.loads(end_time) if isinstance(end_time, str) else end_time
    step_parsed = json.loads(step) if isinstance(step, str) else step

    await _call_tool('query_prometheus', {'cluster_id': cluster_id, 'promql': promql, 'start_time': start_time_parsed, 'end_time': end_time_parsed, 'step': step_parsed})


@call_tool_app.command(name='query_prometheus_metric_guidance')
async def query_prometheus_metric_guidance(
    *,
    resource_label: Annotated[str, cyclopts.Parameter(help="资源维度label：node/pod/container/deployment/daemonset/job/coredns/ingress/hpa/persistentvolume/mountpoint 等")],
    metric_category: Annotated[str, cyclopts.Parameter(help="指标分类：cpu/memory/network/disk/state")],
) -> None:
    '''获取Prometheus指标定义和最佳实践'''
    await _call_tool('query_prometheus_metric_guidance', {'resource_label': resource_label, 'metric_category': metric_category})


@call_tool_app.command(name='diagnose_resource')
async def diagnose_resource(
    *,
    cluster_id: Annotated[str, cyclopts.Parameter(help="需要诊断的ACK集群clusterId")],
    resource_type: Annotated[str, cyclopts.Parameter(help="诊断的目标资源类型，枚举值：node|ingress|memory|pod|service|network")],
    resource_target: Annotated[str, cyclopts.Parameter(help="用于指定诊断对象的参数，参数必须为合法 JSON 字符串（键和值均用双引号），不得输出多余文字。不同类型示例：\n                node: {\"name\": \"cn-shanghai.10.10.10.107\"}，其中name为k8s节点的名称\n                pod: {\"namespace\": \"kube-system\", \"name\": \"csi-plugin-2cg9f\"}， 其中namespace为pod所在的命名空间，name为pod的名称\n                network: {\"src\": \"10.10.10.108\", \"dst\": \"10.11.247.16\", \"dport\": \"80\", \"protocol\":\"tcp\"}， 其中src为源地址，dst为目标地址，dport为目标端口，protocol为协议\n                ingress: {\"url\": \"https://example.com\"}，其中url为ingress的URL地址\n                memory: {\"node\":\"cn-hangzhou.172.16.9.240\"}，其中node为k8s节点的名称\n                service: {\"namespace\": \"kube-system\", \"name\": \"nginx-ingress-lb\"}，其中namespace为service所在的命名空间，name为service的名称\n            ")],
) -> None:
    '''对ACK集群的Kubernetes资源进行诊断，当遇到问题难以定位时，使用该工具进行深度诊断。支持诊断的资源包括：
1. **node**：K8s 节点
2. **ingress**：Ingress
3. **memory**：节点内存
4. **pod**：Pod
5. **service**：Service
6. **network**：网络连通性
                        '''
    await _call_tool('diagnose_resource', {'cluster_id': cluster_id, 'resource_type': resource_type, 'resource_target': resource_target})


@call_tool_app.command(name='query_inspect_report')
async def query_inspect_report(
    *,
    cluster_id: Annotated[str, cyclopts.Parameter(help="需要查询的prometheus所在的集群clusterId")],
    region_id: Annotated[str, cyclopts.Parameter(help="集群所在的regionId")],
    is_result_exception: Annotated[bool, cyclopts.Parameter(help="是否只返回异常的结果，默认为true")] = True,
) -> None:
    '''即可生成并查询一个ACK集群最近的健康巡检报告'''
    await _call_tool('query_inspect_report', {'cluster_id': cluster_id, 'region_id': region_id, 'is_result_exception': is_result_exception})


@call_tool_app.command(name='query_audit_log')
async def query_audit_log(
    *,
    cluster_id: Annotated[str, cyclopts.Parameter(help="The name of the cluster to query audit logs from. if you are not sure, use 'list_clusters' tool to get available clusters.")],
    namespace: Annotated[str | None, cyclopts.Parameter(help="(Optional) Match by namespace. \n    Supports exact matching and suffix wildcards:\n    - Exact match: \"default\", \"kube-system\", \"kube-public\"\n    - Suffix wildcard: \"kube*\", \"app-*\" (matches namespaces that start with the specified prefix)\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"(Optional) Match by namespace. \\n    Supports exact matching and suffix wildcards:\\n    - Exact match: \\\"default\\\", \\\"kube-system\\\", \\\"kube-public\\\"\\n    - Suffix wildcard: \\\"kube*\\\", \\\"app-*\\\" (matches namespaces that start with the specified prefix)\"\n                          }")] = None,
    verbs: Annotated[str | None, cyclopts.Parameter(help="(Optional) Filter by action verbs, multiple values are allowed.\n    Can be a JSON array string like '[\"create\", \"update\"]'.\n    Common values:\n    - \"get\": Get a resource\n    - \"list\": List resources\n    - \"create\": Create a resource\n    - \"update\": Update a resource\n    - \"delete\": Delete a resource\n    - \"patch\": Partially update a resource\n    - \"watch\": Watch for changes to a resource\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"(Optional) Filter by action verbs, multiple values are allowed.\\n    Can be a JSON array string like '[\\\"create\\\", \\\"update\\\"]'.\\n    Common values:\\n    - \\\"get\\\": Get a resource\\n    - \\\"list\\\": List resources\\n    - \\\"create\\\": Create a resource\\n    - \\\"update\\\": Update a resource\\n    - \\\"delete\\\": Delete a resource\\n    - \\\"patch\\\": Partially update a resource\\n    - \\\"watch\\\": Watch for changes to a resource\"\n                          }")] = None,
    resource_types: Annotated[str | None, cyclopts.Parameter(help="(Optional) K8s resource type, multiple values are allowed.\n    Can be a JSON array string like '[\"deployments\", \"pods\"]'.\n    Supports full names and short names. Common values:\n    - Core: pods(pod), services(svc), configmaps(cm), secrets, nodes, namespaces(ns)\n    - App: deployments(deploy), replicasets(rs), daemonsets(ds), statefulsets(sts)\n    - Storage: persistentvolumes(pv), persistentvolumeclaims(pvc)\n    - Network: ingresses(ing), networkpolicies\n    - RBAC: roles, rolebindings, clusterroles, clusterrolebindings\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"(Optional) K8s resource type, multiple values are allowed.\\n    Can be a JSON array string like '[\\\"deployments\\\", \\\"pods\\\"]'.\\n    Supports full names and short names. Common values:\\n    - Core: pods(pod), services(svc), configmaps(cm), secrets, nodes, namespaces(ns)\\n    - App: deployments(deploy), replicasets(rs), daemonsets(ds), statefulsets(sts)\\n    - Storage: persistentvolumes(pv), persistentvolumeclaims(pvc)\\n    - Network: ingresses(ing), networkpolicies\\n    - RBAC: roles, rolebindings, clusterroles, clusterrolebindings\"\n                          }")] = None,
    resource_name: Annotated[str | None, cyclopts.Parameter(help="(Optional) Match by resource name. \n    Supports exact matching and suffix wildcards:\n    - Exact match: \"nginx-deployment\", \"my-service\"\n    - Suffix wildcard: \"nginx-*\", \"app-*\" (matches resource names that start with the specified prefix)\n    \\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"(Optional) Match by resource name. \\n    Supports exact matching and suffix wildcards:\\n    - Exact match: \\\"nginx-deployment\\\", \\\"my-service\\\"\\n    - Suffix wildcard: \\\"nginx-*\\\", \\\"app-*\\\" (matches resource names that start with the specified prefix)\\n    \"\n                          }")] = None,
    user: Annotated[str | None, cyclopts.Parameter(help="(Optional) Match by user name. \n    Supports exact matching and suffix wildcards:\n    - Exact match: \"system:admin\", \"kubernetes-admin\"\n    - Suffix wildcard: \"system:*\", \"kube*\" \\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"(Optional) Match by user name. \\n    Supports exact matching and suffix wildcards:\\n    - Exact match: \\\"system:admin\\\", \\\"kubernetes-admin\\\"\\n    - Suffix wildcard: \\\"system:*\\\", \\\"kube*\\\" \"\n                          }")] = None,
    start_time: Annotated[str, cyclopts.Parameter(help="(Optional) Query start time. \n    Formats:\n    - ISO 8601: \"2024-01-01T10:00:00Z\"\n    - Relative: \"30m\", \"1h\", \"24h\", \"7d\"\n    Defaults to 24h.")] = '24h',
    end_time: Annotated[str | None, cyclopts.Parameter(help="(Optional) Query end time.\n    Formats:\n    - ISO 8601: \"2024-01-01T10:00:00Z\"\n    - Relative: \"30m\", \"1h\", \"24h\", \"7d\"\n    Defaults to current time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"(Optional) Query end time.\\n    Formats:\\n    - ISO 8601: \\\"2024-01-01T10:00:00Z\\\"\\n    - Relative: \\\"30m\\\", \\\"1h\\\", \\\"24h\\\", \\\"7d\\\"\\n    Defaults to current time.\"\n                          }")] = None,
    limit: Annotated[int, cyclopts.Parameter(help="(Optional) Result limit, defaults to 10. Maximum is 100.")] = 10,
) -> None:
    '''Query Kubernetes (k8s) audit logs.

    Function Description:
    - Supports multiple time formats (ISO 8601 and relative time).
    - Supports suffix wildcards for namespace, resource name, and user.
    - Supports multiple values for verbs and resource types.
    - Supports both full names and short names for resource types.
    - Allows specifying the cluster name to query audit logs from multiple clusters.
    - Provides detailed parameter validation and error messages.

    Usage Suggestions:
    - You can use the list_clusters() tool to view available clusters and their IDs.
    - By default, it queries the audit logs for the last 24 hours. The number of returned records is limited to 10 by default.'''
    # Parse JSON parameters
    namespace_parsed = json.loads(namespace) if isinstance(namespace, str) else namespace
    verbs_parsed = json.loads(verbs) if isinstance(verbs, str) else verbs
    resource_types_parsed = json.loads(resource_types) if isinstance(resource_types, str) else resource_types
    resource_name_parsed = json.loads(resource_name) if isinstance(resource_name, str) else resource_name
    user_parsed = json.loads(user) if isinstance(user, str) else user
    end_time_parsed = json.loads(end_time) if isinstance(end_time, str) else end_time

    await _call_tool('query_audit_log', {'cluster_id': cluster_id, 'namespace': namespace_parsed, 'verbs': verbs_parsed, 'resource_types': resource_types_parsed, 'resource_name': resource_name_parsed, 'user': user_parsed, 'start_time': start_time, 'end_time': end_time_parsed, 'limit': limit})


@call_tool_app.command(name='get_current_time')
async def get_current_time(
) -> None:
    '''获取当前时间，返回 ISO 8601 格式和 Unix 时间戳格式'''
    await _call_tool('get_current_time', {})


@call_tool_app.command(name='query_controlplane_logs')
async def query_controlplane_logs(
    *,
    cluster_id: Annotated[str, cyclopts.Parameter(help="集群ID")],
    component_name: Annotated[str, cyclopts.Parameter(help="控制面组件的名称，枚举值： \n                apiserver: API Server组件\n                kcm: KCM组件\n                scheduler: Scheduler组件\n                ccm: CCM组件\n                ")],
    filter_pattern: Annotated[str | None, cyclopts.Parameter(help="(Optional) Additional filter pattern.\n        Example: \n        - 查询pod相关的日志： \"coredns-8bd9456cc-wck2l\"\n        Defaults to '*' (all logs).\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"(Optional) Additional filter pattern.\\n        Example: \\n        - 查询pod相关的日志： \\\"coredns-8bd9456cc-wck2l\\\"\\n        Defaults to '*' (all logs).\"\n                          }")] = None,
    start_time: Annotated[str, cyclopts.Parameter(help="(Optional) Query start time. \n        Formats:\n        - ISO 8601: \"2024-01-01T10:00:00Z\"\n        - Relative: \"30m\", \"1h\", \"24h\", \"7d\"\n        - Current time: \"now\"\n        Defaults to 24h.")] = '24h',
    end_time: Annotated[str | None, cyclopts.Parameter(help="(Optional) Query end time.\n        Formats:\n        - ISO 8601: \"2024-01-01T10:00:00Z\"\n        - Relative: \"30m\", \"1h\", \"24h\", \"7d\"\n        - Current time: \"now\"\n        Defaults to current time.\\nJSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null,\n                            \"description\": \"(Optional) Query end time.\\n        Formats:\\n        - ISO 8601: \\\"2024-01-01T10:00:00Z\\\"\\n        - Relative: \\\"30m\\\", \\\"1h\\\", \\\"24h\\\", \\\"7d\\\"\\n        - Current time: \\\"now\\\"\\n        Defaults to current time.\"\n                          }")] = None,
    limit: Annotated[int, cyclopts.Parameter(help="(Optional) Result limit, defaults to 10. Maximum is 100.")] = 10,
) -> None:
    '''Query ACK cluster control plane component logs.

    Function Description:
    - Queries control plane component logs from ACK clusters.
    - Supports multiple time formats (ISO 8601 and relative time).
    - Supports additional filter patterns for log filtering.
    - Validates component availability before querying.
    - Provides detailed parameter validation and error messages.

    Usage Suggestions:
    - You can use the list_clusters() tool to view available clusters and their IDs.
    - By default, it queries the control plane logs for the last 24 hours. The number of returned records is limited to 10 by default.
    - Supported components: apiserver, kcm, scheduler, ccm, etcd, kubelet, kube-proxy, kube-scheduler, kube-controller-manager, kube-apiserver.'''
    # Parse JSON parameters
    filter_pattern_parsed = json.loads(filter_pattern) if isinstance(filter_pattern, str) else filter_pattern
    end_time_parsed = json.loads(end_time) if isinstance(end_time, str) else end_time

    await _call_tool('query_controlplane_logs', {'cluster_id': cluster_id, 'component_name': component_name, 'filter_pattern': filter_pattern_parsed, 'start_time': start_time, 'end_time': end_time_parsed, 'limit': limit})


@call_tool_app.command(name='analyze_workload_cost')
async def analyze_workload_cost(
    *,
    cluster_id: Annotated[str, cyclopts.Parameter(help="集群 ID")],
    namespace: Annotated[str, cyclopts.Parameter(help="命名空间名称")],
    workload_type: Annotated[str, cyclopts.Parameter(help="工作负载类型")],
    workload_name: Annotated[str, cyclopts.Parameter(help="工作负载名称")],
) -> None:
    '''分析特定工作负载的资源使用情况和成本优化建议。
            
## 使用场景
- 分析单个工作负载的资源配置和实时使用情况
- 评估资源利用率（实际使用 vs requests）
- 获取资源画像推荐配置（如果启用）

## 注意事项
- 利用率可能超过 100%，表示实际使用超过 request 配置
- resource_recommendation 为 null 表示未启用资源画像或没有推荐数据
'''
    await _call_tool('analyze_workload_cost', {'cluster_id': cluster_id, 'namespace': namespace, 'workload_type': workload_type, 'workload_name': workload_name})


if __name__ == "__main__":
    app()
